import { Item } from '@/types/game';

export const ITEMS: Item[] = [
  // Set 1 (Level 1)
  {
    id: 'weapon-1',
    name: 'Ржавый меч',
    type: 'weapon',
    rarity: 'common',
    level: 1,
    price: 200,
    image: '/sets/weapon-1.webp',
    description: 'Старый, покрытый ржавчиной меч.',
    stats: { attack: 5 },
    gemSlots: [null]
  },
  {
    id: 'armor-1',
    name: 'Кожаная куртка',
    type: 'armor',
    rarity: 'common',
    level: 1,
    price: 200,
    image: '/sets/chest-1.webp',
    description: 'Простая кожаная защита.',
    stats: { defense: 3, maxHp: 20 },
    gemSlots: [null]
  },
  {
    id: 'boots-1',
    name: 'Старые сапоги',
    type: 'boots',
    rarity: 'common',
    level: 1,
    price: 160,
    image: '/sets/boots-1.webp',
    description: 'Поношенные сапоги.',
    stats: { defense: 1 },
    gemSlots: []
  },
  {
    id: 'ring-1',
    name: 'Медное кольцо',
    type: 'ring',
    rarity: 'common',
    level: 1,
    price: 300,
    image: '/sets/ring-1.webp',
    description: 'Простое кольцо из меди.',
    stats: { criticalChance: 0.02 },
    gemSlots: []
  },

  // Set 2 (Level 5)
  {
    id: 'weapon-2',
    name: 'Стальной кинжал',
    type: 'weapon',
    rarity: 'common',
    level: 5,
    price: 1000,
    image: '/sets/weapon-2.webp',
    description: 'Острый стальной кинжал.',
    stats: { attack: 15, criticalChance: 0.05 },
    gemSlots: [null]
  },
  {
    id: 'armor-2',
    name: 'Укрепленный доспех',
    type: 'armor',
    rarity: 'common',
    level: 5,
    price: 1000,
    image: '/sets/chest-2.webp',
    description: 'Доспех с железными вставками.',
    stats: { defense: 10, maxHp: 50 },
    gemSlots: [null]
  },
  {
    id: 'boots-2',
    name: 'Кожаные сапоги',
    type: 'boots',
    rarity: 'common',
    level: 5,
    price: 800,
    image: '/sets/boots-2.webp',
    description: 'Добротные сапоги из кожи.',
    stats: { defense: 5 },
    gemSlots: []
  },
  {
    id: 'ring-2',
    name: 'Серебряное кольцо',
    type: 'ring',
    rarity: 'rare',
    level: 5,
    price: 1600,
    image: '/sets/ring-2.webp',
    description: 'Красивое серебряное кольцо.',
    stats: { criticalChance: 0.04, maxMana: 10 },
    gemSlots: [null]
  },

  // Set 3 (Level 10)
  {
    id: 'weapon-3',
    name: 'Боевой топор',
    type: 'weapon',
    rarity: 'rare',
    level: 10,
    price: 4000,
    image: '/sets/weapon-3.webp',
    description: 'Тяжелый боевой топор.',
    stats: { attack: 40 },
    gemSlots: [null, null]
  },
  {
    id: 'armor-3',
    name: 'Кольчуга',
    type: 'armor',
    rarity: 'rare',
    level: 10,
    price: 4000,
    image: '/sets/chest-3.webp',
    description: 'Надежная кольчужная броня.',
    stats: { defense: 25, maxHp: 150 },
    gemSlots: [null, null]
  },
  {
    id: 'boots-3',
    name: 'Стальные сапоги',
    type: 'boots',
    rarity: 'rare',
    level: 10,
    price: 3000,
    image: '/sets/boots-3.webp',
    description: 'Тяжелые стальные сапоги.',
    stats: { defense: 15 },
    gemSlots: [null]
  },
  {
    id: 'ring-3',
    name: 'Золотое кольцо',
    type: 'ring',
    rarity: 'rare',
    level: 10,
    price: 6000,
    image: '/sets/ring-3.webp',
    description: 'Золотое кольцо с гравировкой.',
    stats: { criticalChance: 0.06, maxMana: 30 },
    gemSlots: [null]
  },

  // Set 4 (Level 15)
  {
    id: 'weapon-4',
    name: 'Длинный меч',
    type: 'weapon',
    rarity: 'rare',
    level: 15,
    price: 10000,
    image: '/sets/weapon-4.webp',
    description: 'Отлично сбалансированный меч.',
    stats: { attack: 80, criticalChance: 0.08 },
    gemSlots: [null, null]
  },
  {
    id: 'armor-4',
    name: 'Пластинчатый доспех',
    type: 'armor',
    rarity: 'rare',
    level: 15,
    price: 10000,
    image: '/sets/chest-4.webp',
    description: 'Доспех из стальных пластин.',
    stats: { defense: 50, maxHp: 300 },
    gemSlots: [null, null]
  },
  {
    id: 'boots-4',
    name: 'Латные сапоги',
    type: 'boots',
    rarity: 'rare',
    level: 15,
    price: 8000,
    image: '/sets/boots-4.webp',
    description: 'Прочные латные сапоги.',
    stats: { defense: 30 },
    gemSlots: [null]
  },
  {
    id: 'ring-4',
    name: 'Кольцо силы',
    type: 'ring',
    rarity: 'epic',
    level: 15,
    price: 14000,
    image: '/sets/ring-4.webp',
    description: 'Кольцо, наполненное силой.',
    stats: { attack: 10, criticalChance: 0.10 },
    gemSlots: [null, null]
  },

  // Set 5 (Level 20) - Helmets start here
  {
    id: 'weapon-5',
    name: 'Меч рыцаря',
    type: 'weapon',
    rarity: 'epic',
    level: 20,
    price: 30000,
    image: '/sets/weapon-5.webp',
    description: 'Меч, достойный истинного рыцаря.',
    stats: { attack: 150, criticalChance: 0.12 },
    gemSlots: [null, null, null]
  },
  {
    id: 'armor-5',
    name: 'Рыцарский доспех',
    type: 'armor',
    rarity: 'epic',
    level: 20,
    price: 30000,
    image: '/sets/chest-5.webp',
    description: 'Полный рыцарский доспех.',
    stats: { defense: 100, maxHp: 600 },
    gemSlots: [null, null, null]
  },
  {
    id: 'helmet-5',
    name: 'Рыцарский шлем',
    type: 'helmet',
    rarity: 'epic',
    level: 20,
    price: 24000,
    image: '/sets/helmet-5.webp',
    description: 'Закрытый рыцарский шлем.',
    stats: { defense: 40, maxHp: 200 },
    gemSlots: [null, null]
  },
  {
    id: 'boots-5',
    name: 'Рыцарские сапоги',
    type: 'boots',
    rarity: 'epic',
    level: 20,
    price: 20000,
    image: '/sets/boots-5.webp',
    description: 'Тяжелые рыцарские сапоги.',
    stats: { defense: 40 },
    gemSlots: [null, null]
  },
  {
    id: 'ring-5',
    name: 'Рубиновое кольцо',
    type: 'ring',
    rarity: 'epic',
    level: 20,
    price: 36000,
    image: '/sets/ring-5.webp',
    description: 'Кольцо с огромным рубином.',
    stats: { attack: 30, maxMana: 100 },
    gemSlots: [null, null]
  },

  // Set 6 (Level 25)
  {
    id: 'weapon-6',
    name: 'Меч чемпиона',
    type: 'weapon',
    rarity: 'epic',
    level: 25,
    price: 80000,
    image: '/sets/weapon-6.webp',
    description: 'Меч прославленного чемпиона.',
    stats: { attack: 300, criticalChance: 0.15 },
    gemSlots: [null, null, null]
  },
  {
    id: 'armor-6',
    name: 'Доспех чемпиона',
    type: 'armor',
    rarity: 'epic',
    level: 25,
    price: 80000,
    image: '/sets/chest-6.webp',
    description: 'Легендарная броня чемпиона.',
    stats: { defense: 200, maxHp: 1200 },
    gemSlots: [null, null, null]
  },
  {
    id: 'helmet-6',
    name: 'Шлем чемпиона',
    type: 'helmet',
    rarity: 'epic',
    level: 25,
    price: 70000,
    image: '/sets/helmet-6.webp',
    description: 'Шлем, внушающий страх врагам.',
    stats: { defense: 80, maxHp: 400 },
    gemSlots: [null, null, null]
  },
  {
    id: 'boots-6',
    name: 'Сапоги чемпиона',
    type: 'boots',
    rarity: 'epic',
    level: 25,
    price: 60000,
    image: '/sets/boots-6.webp',
    description: 'Сапоги, не знающие усталости.',
    stats: { defense: 80 },
    gemSlots: [null, null]
  },
  {
    id: 'ring-6',
    name: 'Кольцо вечности',
    type: 'ring',
    rarity: 'legendary',
    level: 25,
    price: 120000,
    image: '/sets/ring-6.webp',
    description: 'Древнее кольцо вечности.',
    stats: { attack: 100, maxMana: 200, criticalChance: 0.05 },
    gemSlots: [null, null, null]
  },

  // Set 7 (Level 30)
  {
    id: 'weapon-7',
    name: 'Меч Дракона',
    type: 'weapon',
    rarity: 'legendary',
    level: 30,
    price: 300000,
    image: '/sets/weapon-7.webp',
    description: 'Меч, выкованный в пламени дракона.',
    stats: { attack: 600, criticalChance: 0.20 },
    gemSlots: [null, null, null, null]
  },
  {
    id: 'armor-7',
    name: 'Чешуя Дракона',
    type: 'armor',
    rarity: 'legendary',
    level: 30,
    price: 300000,
    image: '/sets/chest-7.webp',
    description: 'Броня из чешуи древнего дракона.',
    stats: { defense: 400, maxHp: 2500 },
    gemSlots: [null, null, null, null]
  },
  {
    id: 'helmet-7',
    name: 'Шлем Дракона',
    type: 'helmet',
    rarity: 'legendary',
    level: 30,
    price: 240000,
    image: '/sets/helmet-7.webp',
    description: 'Шлем из черепа дракона.',
    stats: { defense: 150, maxHp: 800 },
    gemSlots: [null, null, null]
  },
  {
    id: 'boots-7',
    name: 'Поступь Дракона',
    type: 'boots',
    rarity: 'legendary',
    level: 30,
    price: 200000,
    image: '/sets/boots-7.webp',
    description: 'Сапоги, дарующие мощь дракона.',
    stats: { defense: 150 },
    gemSlots: [null, null, null]
  },
  {
    id: 'ring-7',
    name: 'Сердце Дракона',
    type: 'ring',
    rarity: 'legendary',
    level: 30,
    price: 400000,
    image: '/sets/ring-7.webp',
    description: 'Кольцо с частицей сердца дракона.',
    stats: { attack: 200, maxHp: 500, maxMana: 300, criticalChance: 0.10 },
    gemSlots: [null, null, null, null]
  },
  // Stones
  {
    id: 'stone-hp',
    name: 'Камень Жизни',
    type: 'stone',
    rarity: 'rare',
    level: 1,
    price: 5000,
    image: '/stones/stone-hp.webp',
    description: 'Магический камень, увеличивающий здоровье на 5%.',
    stats: { maxHp: 0.05 }, // We'll handle percentage in calculation
  },
  {
    id: 'stone-crit',
    name: 'Камень Удачи',
    type: 'stone',
    rarity: 'rare',
    level: 1,
    price: 5000,
    image: '/stones/stone-crit.webp',
    description: 'Магический камень, увеличивающий шанс крита на 2%.',
    stats: { criticalChance: 0.02 },
  },
  // Pets
  {
    id: 'pet-1',
    name: 'Верный щенок',
    type: 'pet',
    rarity: 'common',
    level: 1,
    price: 5000,
    image: '/pets/pet-1.webp',
    description: 'Маленький, но очень храбрый друг. Дает +1% крита и наносит 10 урона в секунду.',
    stats: { criticalChance: 0.01 },
    dps: 10,
  },
  {
    id: 'pet-2',
    name: 'Боевой кот',
    type: 'pet',
    rarity: 'rare',
    level: 1,
    price: 10000,
    image: '/pets/pet-2.webp',
    description: 'Ловкий хищник. Дает +2% крита и наносит 20 урона в секунду.',
    stats: { criticalChance: 0.02 },
    dps: 20,
  },
  {
    id: 'pet-3',
    name: 'Ручной дракончик',
    type: 'pet',
    rarity: 'epic',
    level: 1,
    price: 30000,
    image: '/pets/pet-3.webp',
    description: 'Дышит маленьким пламенем. Дает +3% крита и наносит 30 урона в секунду.',
    stats: { criticalChance: 0.03 },
    dps: 30,
  },
  {
    id: 'pet-4',
    name: 'Призрачный волк',
    type: 'pet',
    rarity: 'epic',
    level: 1,
    price: 50000,
    image: '/pets/pet-4.webp',
    description: 'Дух леса на вашей стороне. Дает +5% крита и наносит 50 урона в секунду.',
    stats: { criticalChance: 0.05 },
    dps: 50,
  },
  {
    id: 'pet-5',
    name: 'Золотой феникс',
    type: 'pet',
    rarity: 'legendary',
    level: 1,
    price: 125000,
    image: '/pets/pet-5.webp',
    description: 'Легендарное создание. Дает +10% крита и наносит 100 урона в секунду.',
    stats: { criticalChance: 0.10 },
    dps: 100,
  },
];
